### ISSUE TITLE
Relocate the top panel (aka menu panel)

### ISSUE THREAD

**Issue by LangLangBart** [LangLangBart/boonGUI#12]
- [x] The menu button should become an icon and
- [x] the civ overview should become visible when clicking on the civ abbreviation in the top statistics panel.

Overall, the journey should go there, some positions like the minimap can be discussed.
AOE4&boonGUI mixUP
![141688064-f4301189-e75f-4be1-aa66-7ef58114b281](https://user-images.githubusercontent.com/92653266/154249661-807e6934-1a9e-48cc-bbb7-c93e433df98a.jpg)

**Comment by neon-marder** [comment]
I agree that the top panel could be nuked if you find another place to put all the stuff.

> Civ Icon : I would like to have it, but don't know where to place it

Could this be an option? [[WIP] Civ backgrounds for minimap.](https://code.wildfiregames.com/D4271)
