### ISSUE TITLE
[IDEA] Toggle top-panel

### ISSUE THREAD

**Issue by readyvivid** [LangLangBart/boonGUI#122]
**Describe your idea**

During team play, the top panel is annoying as it takes up part of the screen. It would be nice if there could be a way to just hide this, like in the right panel.

Or it can be made a little smaller.

**Screenshots**

![Screenshot from 2022-03-28 11-33-19](https://user-images.githubusercontent.com/102513412/160358998-ddc5d81b-f146-4d28-b534-f7a08ca0cc93.png)

**Comment by LangLangBart** [comment]
Little button below the minimap, but this hides everything, you won't even see the resources.

<img src="https://ttm.sh/iyq.09.jpg" width="400">

**Comment by LangLangBart** [comment]
Alternatively, it could be rewritten to hide only the allies and only show the top panel stats of the active player. Share you thoughts.

**Comment by readyvivid** [comment]
> Alternatively, it could be rewritten to hide only the allies and only show the top panel stats of the active player. Share you thoughts.

I'm using it with Autociv. I use Autociv for hotkeys, it would be better if the hotkeys in autociv are integrated into BoonGUI and the feature you mentioned is done.

**Comment by LangLangBart** [comment]
> and the feature you mentioned is done.
The positioning of the buttons to toggle the top/side panel of stats is not optimal. I heard this issue from a couple of players before. Related #120  

>  I use Autociv for hotkeys, it would be better if the hotkeys in autociv are integrated into BoonGUI

Do I understand correctly that the hotkeys in Autociv do not work properly when you use the Boongui mod as well? I've never worked much with hotkeys, but I usually test the selection of all cavalry units with `Alt+E`, so I assumed that everything works fine. 

I'm closing the ticket for now, but the hotkey issue could become a new issue depending on the response.
