### ISSUE TITLE
[IDEA] Remove working elephants from a special idle list

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#135]
Remove working elephants from the idle list

i not sure about my idea. maybe its possible and good to remove working ele from the idle the idle list.

### motivation / problem:
i often use 
Alt+#  for select idle and send them to work.
and in next step i select working ele for prevent that it is moving (btw my hotkey is Alt+E (e for elephant) bzw. wor warElefant i use Alt+W)

### cons
idle means indle and not for some idle. that makes confusing. 
any ide? or there already solutions for this?

**Comment by LangLangBart** [comment]
`Alt+#` will select any idle unit. There are some other hotkeys you can take adavnatge of.
The elephant is neither a `Worker, Builder or Warrior`.
<img src="https://trac.wildfiregames.com/raw-attachment/wiki/FAQ/idle_hotkeys.jpg" width="600">
