### ISSUE TITLE
[Feature]:  I want to use the default top panel

### ISSUE THREAD

**Issue by mehdrad12** [LangLangBart/boonGUI#154]
### Before You Submit Your Feature Request

- [x] I have searched the [issue tracker](https://github.com/LangLangBart/boonGUI/issues) for a feature request that matches the one I want to file, without success.

### Problem

The top panel is unnecessarily bloated and distracting. I just want to use the right panel. 

### Feature/ Solution

What files do I need to extract for this?
maybe you can create a branch for top panel external boongui

**Comment by LangLangBart** [comment]
If I understand your request correctly, you want it to look like picture `C`. If this is the case, I will close the ticket as I have no intention to appear like that.

<img src="https://ttm.sh/wR3.jpg" width="600">


For modding you would need to work with the [stats folder](../blob/main/gui/session/stats).

If I have misunderstood your request, please reopen the ticket.

**Comment by mehdrad12** [comment]
Hello again, yes I wanted something like option C.
The default boongui in team play is too distracting.
