### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by LangLangBart** [LangLangBart/boonGUI#19]
0ad provides a set of nice tools to test the impact of code changes on performance.

Test the boonGUI mod with the new changes and compare it to the base game.
Share results here.

- [wiki/EngineProfiling](https://trac.wildfiregames.com/wiki/EngineProfiling)

**Comment by LangLangBart** [comment]
### Performance is bad.
The **boonGUI mod 2.0** with the latest changes contributes massively to the already existing lag. Testing it on 3v3 (_Mainland - Medium - 200Pop_ )with the [In-game profiler](https://trac.wildfiregames.com/wiki/EngineProfiling#In-gameprofiler).
Replay file used for testing: [commands.txt](https://github.com/LangLangBart/boonGUI/files/7552265/commands.txt)


#### Autociv: Mostly below 1msec/turn
![autociv_lag](https://user-images.githubusercontent.com/92653266/142145597-5f3de438-d651-4bea-acc6-044b3e237186.jpg)

#### boonGUI 1.7:  Mostly below 3 msec/turn
![boongui_1_7_lag jpg](https://user-images.githubusercontent.com/92653266/142149015-40551936-0f00-46e1-816d-5b4398dccdc5.jpg)

#### boonGUI 2.0: 30-50 msec/turn
![boongui_2_0_lag](https://user-images.githubusercontent.com/92653266/142149024-33def58b-2fb1-4f34-b54f-71f7f254fcfe.jpg)

### To reduce the load and increase the performance:
* increase the [tickPeriod](https://github.com/LangLangBart/boonGUI/blob/26d6f02d43c241391a2e34ebea05e29ac0a42db9/gui/session/stats/BoonGUIStats.js#L19) 
* decrease the number of elements being updated
* If you turn it off, you can still use the other features of the mod, but the stats overlay should be off by default if you are actively playing a game.

### Contacting consultants and asking for advice
1. I already asked badosu for advice to avoid additional lag without killing too many features of the mod. (Status: No response yet)
2. Will also ask nani via the forum today.
3. Asking elexis tonight via IRC.

**In its current form, the mod should not be released because it is causing too much lag.**

**Comment by nanihadesuka** [comment]
@LangLangBart your call to the Engine to get the stats is probably the culprit.  I've seen the GuiInterface method and it just passes too much stuff, the conversion between the JS simulation -> C++ -> JS GUI is an expensive operation. In my opinion you have two options 1) Cut the number of stats you send 2) create a differential of the data in the JS simulation context comparing it with the last stats you sent. 1) is easier and will improve performance 2) Will take more work and is possible 
 it doesn't fix the problem.

**Comment by LangLangBart** [comment]
Counting the time till the agme reaches the 20min mark:
**for boonGUI 2.0.1** 
* 23:53

![Screenshot 2021-11-19 at 14 25 05](https://user-images.githubusercontent.com/92653266/142666528-019e06ca-8716-424d-b9b5-29e19bb31f38.jpg)

**for vanilla**
* 23:43

![Screenshot 2021-11-19 at 13 57 27](https://user-images.githubusercontent.com/92653266/142666559-8c3bc82e-3e5c-4069-ab91-d29b2ce671cb.jpg)

This 10seconds difference is only for a 3v3 with 200 pop limit. I would still vote to disable the stats overlay for active players or add a timeout timer to it. Observers are decoupled, so it doesn't matter too much if they lag.

**Comment by LangLangBart** [comment]
Adding badosu's comment here, to have it all in one place:

> Generally you want to separate draw from calculations and minimize both, calculate what you need to calculate in a loop dissociated with draw and with the delta that is not too long to be stale and not too short to be updating on every frame (it also helps with not distracting much with the bar updating all the time).
> The drawings should only happen if a change has happened to the calculated concerned variables, I think that's the gist of it.
> In prodmod I separated the calculations from drawing with the monitor classes and the modular services that calculate the concerned variables. MonitorManager for example here: [MonitorManager.js](https://github.com/badosu/prodmod/blob/master/gui/session/MonitorManager.js)
> You also want to minimize calls to engine and retrieve data just once per calculated frame and cache it.
