### ISSUE TITLE
Update the main menu

### ISSUE THREAD

**Issue by LangLangBart** [LangLangBart/boonGUI#25]
The main menu was put together quickly and without much thought, there is room for improvement.
Marder has already provided a working mod to drastically improve the overall layout, and allows it to be added to the boonGUI mod.
- Related forum thread: [shiny - an alternative main menu UI](https://wildfiregames.com/forum/topic/54074-shiny-an-alternative-main-menu-ui/) (28/Aug/21)
![screenshot1219 thumb png c96d4bc296aa43b2014c09caa90dc02d](https://user-images.githubusercontent.com/92653266/141694210-4906fb8f-734a-4d54-b69e-3a696d7b4a53.png)

**Comment by neon-marder** [comment]
v2.0 is in progress

**Comment by LangLangBart** [comment]
This will be left to the main game
