### ISSUE TITLE
Gather rates OR current number of gatheres NOT both.

### ISSUE THREAD

**Issue by LangLangBart** [LangLangBart/boonGUI#30]
After testing the latest version with the additional gather rates, I would argue against including both numbers in the stats overlay next to the resource amounts.
I would recommend:
- keeping the gather rates and killing the number of gatherers or
- adding an option that allows the player to adjust the numbers to their personal preferences.
![rates](https://user-images.githubusercontent.com/92653266/141744256-8115fe36-6912-48c2-beb6-227ecceb320b.jpg)

I think that the income you generate over a certain period of time (e.g. 10 seconds) is more important to see than the number of gatherers, because then you would also have to check the eco upgrades to analyze the economic situation of the player. That's why I always prefer the gather rates over the number of gatherers.

**Comment by IlanFrumer** [comment]
I think you are correct.
I will keep the gather rates visible and add a tooltip with more information:
- amount of gatherers
- resource related upgrades
