### ISSUE TITLE
Stats overlay main/expanded view

### ISSUE THREAD

**Issue by LangLangBart** [LangLangBart/boonGUI#5]
Currently the Stats Overlay displays the following columns:
![Screenshot 2021-11-14 at 11 48 02](https://user-images.githubusercontent.com/92653266/141683204-aa5c87d2-9e0a-4854-b81f-1db2a6a2f4f2.jpg)

There was discussion about adding a small button in the upper right corner of the statistics overlay, next to "K/D", to display an expanded view with more stats. For a suitable icon, see the list of recommended links in Issue #4.
![Screenshot 2021-11-14 at 11 48 02](https://user-images.githubusercontent.com/92653266/141683400-518254c7-193b-4231-96a5-fdee3d1dab07.jpg)
![image thumb png dbfb7b7571c01caf1cb891aef4ec9e29 png bfab005232aa94aaa02e8e93f56c2481-1](https://user-images.githubusercontent.com/92653266/141683542-35f11c8c-35eb-4e60-8479-87394b154c49.png)

### Main Screen should have

- Team, Player, Rating, Civ, Phase, Pop
- Number of Support units (Sup), Total Number of Military units (Army)
- Infantry & Cavalry units
- Champion units (mysticjim loves it)
- Siege units (I would put war elephants& siege units together)
- Resources (Food, wood, stone, metal)
- Kills, deaths, K/D
- little cartography indicator (I love this, don't want to miss it)

NOTE: I would not add a tech column because the display in the overlay on the right is more useful than seeing the total number of techs; however, it can be added in the expanded view. If there is a good argument for including it on the main screen, I would be open to it.
### Expanded Screen should have
Up to you islan. Scores, tech, Mele, ranged, ...

**Comment by LangLangBart** [comment]
Personally, I don't think we need an expanded view, the "BoonGUIStatsModes" on the right do such a good job of presenting useful information that it seems unnecessary.

**Comment by neon-marder** [comment]
I agree with @LangLangBart . For me, the expanded view would be unnecessary now with the new stats on the right.

**Comment by LangLangBart** [comment]
@IlanFrumer I've received feedback from 2 different sources and I'm also not a fan of adding more to the stats overlay. You are still assigned to it, have you already started working on it, if not I will close the ticket in the coming days.

**Comment by LangLangBart** [comment]
No need for expanded view.
