### ISSUE TITLE
After advancing, icon for town and city phase shows "I"

### ISSUE THREAD

**Issue by andy5995** [LangLangBart/boonGUI#58]
* v2.0.0

In the player stats overlay, the icon that displays which phase the player has reached shows a "I" even after they've reached town or city phase.

I accidentally captured this phenomenon in [this video](https://www.twitch.tv/videos/1210157681) (which will expire after 2 weeks, btw).

**Comment by LangLangBart** [comment]
Hey, thanks for the report.
I think I manged to fix it in 2.0.1
**Related issue:**
* https://github.com/LangLangBart/boonGUI/issues/55

**Comment by andy5995** [comment]
Ah, nice.
