### ISSUE TITLE
Disable the stats panel in the top left when playing / for non-observers

### ISSUE THREAD

**Issue by neon-marder** [LangLangBart/boonGUI#59]
When actively playing the game, I would like to use all UI improvements, but I don't need / want to see the top left stats panel.
For one, it is in some parts redundant to the information in the top bar and it also feels to me like information overload.

I would suggest disabling the stats panel while actively playing (which should also have the bonus of easing the performance impact #19 ) and only showing it when observing a game.

**Comment by LangLangBart** [comment]
Either:
1. disable them completely or 
2.at least keep it hidden for active players when spawning into the game. They can then still use it if they want.

If the latter option is chosen, we should also add a note about disabling the stats overlay to increase the performance to the minimap button. (Definetly some color, a nice font and adjust the tooltip_style.)

for example like this
![perform](https://user-images.githubusercontent.com/92653266/142729232-66d08007-58f1-42cb-a6f6-eda329d04e8a.jpg)
.

**Comment by LangLangBart** [comment]
Adding an idea from the forum to this issue request when you resign the stats overlay should automatically appear.
Realetd forum topic: [boonGUI mod (compatible with A25)](https://wildfiregames.com/forum/topic/37147-boongui-mod-compatible-with-a25/?do=findComment&comment=465822)
> badosu: Also, it would be nice to be able to enter spec mode after resigning.
