### ISSUE TITLE
[IDEA] doubleClick or singleClick in stats focus the cc of the player

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#76]
helpful in replay.
i sometimes click in the stats (top right) with the hope then to jump to the player. maybe a good idea i think.

**Comment by Pretuer** [comment]
Coud you elaborate more on what you mean by this I don't fully understand

**Comment by LangLangBart** [comment]
Yes, we had this feature in [prodmod](https://github.com/badosu/prodmod) by badosu.
It would be a good addition when clicking on the player colored columns or civ icon
![jump_to](https://user-images.githubusercontent.com/92653266/144779196-6249098c-e2e4-49d5-b0b2-3abc99fdbc3e.gif)
.
