### ISSUE TITLE
[IDEA] real rating into the stats

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#78]
some players changed name, for example by using custom rating name.
is it maybe interesting to get the real rating into the rating column in to the stats top left?
![image](https://user-images.githubusercontent.com/5634759/145897272-c37fe5b4-2bf7-47f4-8681-49aade90bad4.png)

**Comment by sl5net** [comment]
maybe helpful source in the mod customRating

customrating0.25.2/gui/gamesetup_mp/gamesetup_mp.js:495

```
        Engine.StartNetworkJoinLobby(playername + (g_UserRating ? " (" + g_UserRating + ")" : ""), hostJID, password);
```

**Comment by LangLangBart** [comment]
So in theory it should be possible to show the correct rating when connected to the lobby and pulling the data from the server.
I won't fix it and leave the ticket open for now, the bot will close it in time or someone else will fix it.
