### ISSUE TITLE
[BUG] Option to send tribute to enemy is gone 

### ISSUE THREAD

**Issue by LastLightSith** [LangLangBart/boonGUI#84]
**Describe the bug**
Sometimes in FFA, I need to give my enemy some tribute. but when boonGUI is enabled, I can't do that. If I make my enemy neutral, I can send them tribute but teams are locked in most games

**Mod version**
v2.1x

**Comment by LangLangBart** [comment]
![tribute](https://user-images.githubusercontent.com/92653266/150102751-ade2718e-2ce8-4732-bdb7-08bc275a2089.gif)

**Comment by LastLightSith** [comment]
wow that quick. Thanks
